name: chess_repository
description: Chess Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  json_serializable: ^6.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.0.0
